apiVersion: v1
kind: Service
metadata:
  name: nginxp-microgw-e-svc
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: nginxp-microgw-f
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxp-microgw-f-deploy
spec:
  selector:
    matchLabels:
      app: nginxp-microgw-f
  replicas: 1
  template:
    metadata:
      labels:
        app: nginxp-microgw-f
    spec:
      containers:
      - name: nginxp-microgw-f
        image: reg.foobz.com.au/foobz/nginx-plus-ctrl-agent:slim_r18
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
      - name: fluentd
        image: reg.foobz.com.au/foobz/fluentd
        imagePullPolicy: IfNotPresent
        env:
        - name: FLUTNTD_ARGS
          value: -c /etc/td-agent/td-agent.conf
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: config-volume
          mountPath: /etc/td-agent
      volumes:
        - name: nginx-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: sc-fluentd-apigw-td-configmap
