---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: database
spec:
  selector:
    name: mongodb
    app: database
  ports:
  - port: 27017
    name: db-port
    targetPort: 27017

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: database
spec:
  containers:
  - name: mongodb
    image: mongo:4.0.2
    ports:
    - containerPort: 27017
